model:
  base_learning_rate: 1.0e-5
  weight_decay: 0.01
  target: ldm.models.diffusion.ddpm_edit.LatentDiffusion
  params:
    fp16: True
    deepspeed: 'deepspeed_1'
    ckpt_path: checkpoints/v1-5-pruned-emaonly-adaption-task.ckpt
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: edited
    cond_stage_key: edit
    image_size: 32
    channels: 4
    cond_stage_trainable: true   # Note: different from the one we trained before
    conditioning_key: hybrid
    monitor: val/loss_simple_ema
    scale_factor: 0.18215

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 100 ]
        cycle_lengths: [ 20000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-4 ]
        f_max: [ 1. ]
        f_min: [ 0.1 ]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 8
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False
        force_type_convert: True

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
      params:
          version: "/home/intern4/.cache/huggingface/hub/models--openai--clip-vit-large-patch14/snapshots/32bd64288804d66eefd0ccbe215aa642df71cc41"
          # version: "/home/intern4/.cache/huggingface/hub/models--microsoft--BiomedNLP-BiomedBERT-base-uncased-abstract/snapshots/d673b8835373c6fa116d6d8006b33d48734e305d"
  

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 96
    num_workers: 4
    train:
      - train_ds1:
        target: dataset.brain_mri.brain_mri.BrainMRIDataset
        params:
          path: /fast_storage/intern/data/instruction_tuning/IP_Adapter/segmentation_mat/
          split: train
          sample_weight: 0.75
      - train_ds2:
        target: dataset.brain_mri.brain_mri.BrainMRIDataset
        params:
          path: /fast_storage/intern/data/instruction_tuning/IP_Adapter/crossmodal_mat/
          split: train
          sample_weight: 0.75
      # - train_ds3:
      #   target: dataset.brain_mri.brain_mri.BrainMRIDataset
      #   params:
      #     path: /fast_storage/intern/data/instruction_tuning/IP_Adapter/denoising_mat/
      #     split: train
      #     sample_weight: 1.0
      # - train_ds4:
      #   target: dataset.brain_mri.brain_mri.BrainMRIDataset
      #   params:
      #     path: /fast_storage/intern/data/instruction_tuning/IP_Adapter/acceleration_mat/
      #     split: train
      #     sample_weight: 1.0

    validation:
      - val_ds1:
        target: dataset.brain_mri.brain_mri.BrainMRIDataset
        params:
          path: /fast_storage/intern/data/instruction_tuning/IP_Adapter/segmentation_mat/
          split: val
          sample_weight: 0.75
      - val_ds2:
        target: dataset.brain_mri.brain_mri.BrainMRIDataset
        params:
          path: /fast_storage/intern/data/instruction_tuning/IP_Adapter/crossmodal_mat/
          split: val
          sample_weight: 0.75
      # - val_ds3:
      #   target: dataset.brain_mri.brain_mri.BrainMRIDataset
      #   params:
      #     path: /fast_storage/intern/data/instruction_tuning/IP_Adapter/denoising_mat/
      #     split: val
      #     sample_weight: 1.0
      # - val_ds4:
      #   target: dataset.brain_mri.brain_mri.BrainMRIDataset
      #   params:
      #     path: /fast_storage/intern/data/instruction_tuning/IP_Adapter/acceleration_mat/
      #     split: val
      #     sample_weight: 1.0

    test:
      - test_ds1:
        target: dataset.brain_mri.brain_mri.BrainMRIDataset
        params:
          path: /fast_storage/intern/data/instruction_tuning/IP_Adapter/segmentation_mat/
          split: test
          sample_weight: 1.0
      - test_ds2:
        target: dataset.brain_mri.brain_mri.BrainMRIDataset
        params:
          path: /fast_storage/intern/data/instruction_tuning/IP_Adapter/crossmodal_mat/
          split: test
          sample_weight: 1.0
      # - test_ds3:
      #   target: dataset.brain_mri.brain_mri.BrainMRIDataset
      #   params:
      #     path: /fast_storage/intern/data/instruction_tuning/IP_Adapter/denoising_mat/
      #     split: test
      #     sample_weight: 1.0
      # - test_ds4:
      #   target: dataset.brain_mri.brain_mri.BrainMRIDataset
      #   params:
      #     path: /fast_storage/intern/data/instruction_tuning/IP_Adapter/acceleration_mat/
      #     split: test
      #     sample_weight: 1.0

trainer:
  initial_scale: 12
  max_epochs: 40
  save_freq: 4
  accumulate_grad_batches: 1
  clip_grad: 1.0
  optimizer: adamw